import { NextRequest, NextResponse } from 'next/server'

/**
 * DEPRECATED: DOCX generation now happens in the worker
 * 
 * This endpoint is kept for backward compatibility but returns 410 Gone.
 * All DOCX/Anki files are now generated by the worker and available via
 * the outputs_json in the job status.
 */
export async function POST(request: NextRequest) {
  return NextResponse.json(
    { 
      error: 'This endpoint is deprecated. DOCX files are now generated by the worker and available in job outputs.',
      code: 'ENDPOINT_DEPRECATED'
    }, 
    { status: 410 }
  )
}